### ISSUE TITLE
Remove PocketAPRS map format (.pdb)

### ISSUE THREAD

**Issue by we7u** [Xastir/Xastir#117]
I propose we remove the PocketAPRS map format entirely from the Xastir project (*.pdb files). It's doubtful anyone would still be using the format, but if so there are plenty of newer maps to choose from these days.

**Comment by tvrusso** [comment]
Let's do it.  It is highly unlikely anyone is still using maps intended for turn-of-the-century PDAs.

Changing title.

**Comment by we7u** [comment]
PR #120 deals with this.
