### ISSUE TITLE
Make rtree unconditional instead of optional, remove alternate code

### ISSUE THREAD

**Issue by tvrusso** [Xastir/Xastir#127]
The "--with-rtree" option in configure is a relic of the days when rtree was an experimental feature and we were still deciding whether it helped at all.

Without rtree, shapefile rendering is done first by checking if the entire file's bounding box overlaps the current screen, and if it does overlap the code proceeds by sequentially reading each shape from the file and testing each one against the bounding box of the current view to decide whether to draw it or not, then drawing it and performing any clipping necessary.  This is done every time the map is zoomed or panned, and for shapefiles covering large areas (e.g. a CONUS-level road map) it can be very slow, especially if the current view actually excludes most shapes in the file.

With rtree, a spatial index data structure (an R-tree, https://en.wikipedia.org/wiki/R-tree) is constructed for each selected shapefile, indexing the bounding boxes of every shape in the shapefile.  Then, when time comes to render that shapefile, a fast query of "which shapes overlap this bounding box?" produces a (generally) small list of which shapes to read, and those are read by direct access instead of sequentially.    No benefit at all is obtained if the entire shapefile bounding box is enclosed by the current screen view, and the map_shp code is actually smart enough not to bother using the rtree if every shape in the file is supposed to be drawn anyway.

There are a lot of tradeoffs in this --- the rtree data structures take up RAM, and if not much zooming and panning is being done, they don't help.  So there is code in Xastir to apply timeouts to the rtree data structures and delete them after they haven't been used for a while.  If one then zooms and pans again, the rtrees have to be reconstructed.  So there is a somewhat arbitrarily chosen space/time tradeoff being applied.  In actual operation of Xastir on any modern computer created since this feature was added, this tradeoff is unnoticable, and hasn't been commented on in the 13 years that rtree has been the default in Xastir.

Another tradeoff made is that if the entire shapefile is enclosed in the screen bounding box, we don't even *generate* an rtree for it until such time as the screen bounding box is moved to merely *intersect* the shapefile's bounding box.  

It was established long ago that this was a beneficial feature, and it has been the default operation of Xastir since commit cf417d17 in 2006.  The rtree library is bundled in Xastir, not an external dependency, so there is no real value to maintaining it as a user-selectable option, nor is there a lot of value in maintaining the old sequential-access code.

I recommend that we remove the sequential access code, remove the various configure tests for disabling rtree, and just make Xastir use the current, default, efficient access method instead.  The result will be less code bloat, simpler autoconf and automake setup, and more maintainability.

In map_shp.c, this would mostly be a matter of removing various "#ifdef USE_RTREE" ifdefs, and tossing the code in the "#else" blocks.

Obviously, this should not happen until well after the next release.

**Comment by we7u** [comment]
+1. Agree wholeheartedly.
