### ISSUE TITLE
Make dbfawk the only way to render shapefiles

### ISSUE THREAD

**Issue by tvrusso** [Xastir/Xastir#128]
Currently, dbfawk and the pcre library it requires are separate configuration options (this is a mistake, actually, as requesting dbfawk *requires* pcre, and pcre is used for nothing else --- so it should always have been just ONE option).  When enabled (the default), shapefiles are rendered by first checking if a "dbfawk" file exists to describe how to render the data, and if so, using it to set various rendering options like color, line width, line style, fill style, label size, and even what zoom level at which the feature should no longer be rendered.  If no dbfawk is found, a default (ugly) rendering style is used.

Without dbfawk, shapefile rendering is done by a hard-coded rendering choices that in many cases are based on the file name of the shapefile.

As a result, map_shp.c is peppered with "#ifdef WITH_DBFAWK" ifdefs, making it very difficult to read and work on without the potential of breaking the code that's ifdefed out and probably rarely getting compiled.

dbfawk has been the default  shapefile rendering method since commit 91d3e468 in 2004, and the proliferation of new ".dbfawk" files in our repo to "pretty up" various special use shapefiles as they get discovered is a testimony to the fact that it is being used and used well.

I propose that we simplify our configure process and simplify map_shp.c by making dbfawk the *only* shapefile rendering method.  This requires that we make pcre a mandatory dependency if shapelib is enabled, removing all the ifdef'd code that would be compiled if dbfawk were deselected, removing the ifdefs on "WITH_DBFAWK", and removing the configure option.

Pros:  Simpler, more maintainable code; fewer unnecessary configure choices
Cons: makes pcre mandatory instead of optional for shapefile rendering.

Not suggesting that this be done right away, and certainly not until long after our next release (2.1.2?  2.2.0?)

**Comment by we7u** [comment]
+1

**Comment by tvrusso** [comment]
Jason --- I'm ready to make a pull request on this, so I've deassigned you and reassigned me.  I'm writing the PR now.
