### ISSUE TITLE
lclint annotation: "/*@unused@*/" needed anymore?

### ISSUE THREAD

**Issue by we7u** [Xastir/Xastir#136]
Years ago I added /*@unused@*/ in function declarations where the parameter wasn't used. This was for lclint checking of the code to get rid of hundreds or thousands of warnings. Do we need this in the code anymore? We have similar notations for the compiler now and those are more accurate. If people agree with removing them I'll yank them out of the code for good.

**Comment by tvrusso** [comment]
I do not now use, nor have I ever used, lclint.  I'm cool with removing the
/* unused */ tags if you are.

**Comment by we7u** [comment]
Closed by PR #137.
