### ISSUE TITLE
Travis-CI builds don't build Davis or LaCrosse code

### ISSUE THREAD

**Issue by we7u** [Xastir/Xastir#142]
We build in the src and callpass directories with Travis-CI but we don't build in the Davis or LaCrosse directories. We should include those in the Travis-CI builds so we build all of the code.

**Comment by tvrusso** [comment]
That means installing more dependent libraries --- those codes both need mysql libraries.

**Comment by we7u** [comment]
Yea, still researching how to do that correctly with Homebrew on OSX.

**Comment by we7u** [comment]
I'll probably need Jason's help on this one. I'm getting tired of trying random things via Travis-CI. Would be good if someone who had direct access to OSX could give me the things to add to the Travis-CI config.

**Comment by godfreja** [comment]
The Minnesota MS150 bike ride is coming up this weekend so I am fairly busy. I will try to look at this after that event.

**Comment by we7u** [comment]
No problemo. What I've done is here:
  https://github.com/we7u/Xastir/tree/travis
The three Linux builds are compiling Davis & Lacrosse but the OSX build isn't. It's somewhat close to working but I can't figure out where the mysql.h include file is that it needs w/o a running system to play with. By the way: The mysql-connector-c package added a trailing "-l" in the link, apparently a known problem, which is why I switched to the mariadb-connector-c package.

**Comment by we7u** [comment]
I'm going to commit my Travis-CI config changes to the master project. Everything's working except the Davis/Lacrosse pieces of the OSX build. I can wait until Jason works on that, it's not critical. Davis/Lacrosse pieces are commented-out for OSX so that it compiles, but those pieces are compiling successfully in the Linux builds.
