### ISSUE TITLE
ridge_radar.pl

### ISSUE THREAD

**Issue by texnusn** [Xastir/Xastir#161]
Just a simple correction on line 28 and 41. It should read 

my $gif_url = 'https://radar.weather.gov/ridge/RadarImg/N0R/' .  $station . '_N0R_0.gif';

HTTP::Request->new( GET => 'https://radar.weather.gov/ridge/RadarImg/N0R/' . $station .  '_N0R_0.gfw' )

not 

my $gif_url = 'http://radar.weather.gov/ridge/RadarImg/N0R/' .  $station . '_N0R_0.gif';

HTTP::Request->new( GET => 'http://radar.weather.gov/ridge/RadarImg/N0R/' . $station .  '_N0R_0.gfw' )

**Comment by tvrusso** [comment]
When I run the script as is, it works just fine with the http.  But you're correct, it should be https: because the http: version is just redirecting to https anyway.  I've fixed it.
