### ISSUE TITLE
Build error with -fno-common or GCC-10

### ISSUE THREAD

**Issue by dl1jbe** [Xastir/Xastir#164]
While testing with GCC-10 (which uses -fno-common) as default we get some build errors:

`/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: x_spider.o:(.bss+0x0): multiple definition of `pname'; db.o:(.bss+0x408): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: xa_config.o:(.bss+0x0): multiple definition of `xa_config_dir'; color.o:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: xa_config.o:(.bss+0x3e8): multiple definition of `number_of_predefined_objects'; db.o:(.bss+0x0): first defined here
`

System info: Gentoo Linux on x86_64 system.

**Comment by tvrusso** [comment]
Closed by PR #165
