### ISSUE TITLE
Pan and Zoom Buttons not responding

### ISSUE THREAD

**Issue by k7bls** [Xastir/Xastir#169]
I updated Xastir to V2.1.7
It’s running on RPi 4b under version 10 buster

When I click on In, Out, or the four pan buttons nothing happens. It worked on V2.1.5
Mouse clicks on the other menu items work fine
Right click on the map opens the Options menu. Zoom Level and Pan work fine

Suggestions?

Thanks

**Comment by tvrusso** [comment]
Working fine for me.

Check that you haven't accidentally enabled "Disable Fast Zoom/Pan/Home" under
the Map menu.  It disables those buttons.

On Sun, May 31, 2020 at 04:25:33PM -0700, we recorded a bogon-computron collision of the <notifications@github.com> flavor, containing:
> I updated Xastir to V2.1.7
> It???s running on RPi 4b under version 10 buster
> 
> When I click on In, Out, or the four pan buttons nothing happens. It worked on V2.1.5
> Mouse clicks on the other menu items work fine
> Right click on the map opens the Options menu. Zoom Level and Pan work fine
> 
> Suggestions?
> 
> Thanks
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Xastir/Xastir/issues/169

-- 
Tom Russo    KM5VY
Tijeras, NM  

 echo "prpv_a'rfg_cnf_har_cvcr" | sed -e 's/_/ /g' | tr [a-m][n-z] [n-z][a-m]

**Comment by k7bls** [comment]
Thanks. I unchecked "Disable Fast Zoom/Pan/Home" and it’s working now 

As the station engineer at KBOO-FM said. “It’s always a switch”
