### ISSUE TITLE
New URL for FCC database download

### ISSUE THREAD

**Issue by drboone** [Xastir/Xastir#171]
The `get-fcc-rac.pl` callsign fetcher fails to get the FCC data.  It looks like the current URL for the l_amat file is:
`ftp://wirelessftp.fcc.gov/pub/uls/complete/l_amat.zip`.

**Comment by tvrusso** [comment]
That is exactly the URL used in the current version of get-fcc -rac.pl ever since commit b17a63bbdfac4422612a99e8acc89c9b4f619340 on October 3rd.

Update your sources from git master branch and install again, and it should work.
