### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by drboone** [Xastir/Xastir#177]
I notice the SSL cert on xastir.org is expired.

**Comment by tvrusso** [comment]
Thanks for pointing that out.  Looks like it expired in March.

I believe @we7u owns that domain and will have to look into the certificate.  Hopefully he'll be able to get a new one generated.

**Comment by tvrusso** [comment]
Thank you for reporting this.  Curt has renewed the certificate and all should be well now.
