### ISSUE TITLE
Add a better quality desktop icon

### ISSUE THREAD

**Issue by AsciiWolf** [Xastir/Xastir#220]
The [current desktop icon](https://github.com/Xastir/Xastir/blob/master/symbols/icon.png) is too small for today's standards/package managers and causes Xastir to be hidden from software centers in Ubuntu and other Linux distributions. Please, consider adding at least a 128 x 128 px png file or a scalable svg one.

This is a svg file that we made for our Fedora Linux Xastir package:

![xastir](https://github.com/user-attachments/assets/53693c68-6d3c-42bf-a7f6-880fba5dfdc4)

**Comment by tvrusso** [comment]
Is it necessary to replace the existing, small icon, or can we simply provide the original, your upscaled png, and this SVG and satisfy everyone?

I'm reviewing your pull request, and it replaces the icon completely with a much larger one.  I'd prefer to expand the choices.
