### ISSUE TITLE
Review contents of LICENSE file and remove inappropriate license inclusions.

### ISSUE THREAD

**Issue by tvrusso** [Xastir/Xastir#31]
The LICENSE file in the Xastir source lists the license of every single library that Xastir may pull in, and does not necessarily represent an appropriate accounting of the license of the code in the Xastir repository.  This may cause some distributions or packaging systems to mark Xastir as not being completely GPL code, just based on what we're saying in that file.

We should make this document clearer, and make it actually reflect the license that pertains to the code in the repository.   If it is absolutely necessary to document every single license of every single third party library we might optionally link to, then that should be clearly delineated in the document.

This has already caused some consternation that is delaying adoption of Xastir in a package management system.  c.f. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226187

**Comment by 0mp** [comment]
I am sorry for causing additional delays. :(

The LICENSE variable in FreeBSD Ports is often missing or filled in with invalid information. This is why I checked out LICENSE and COPYING as a part of the review. 

Thanks for cleaning it up! Hopefully, the Xastir port will be updated soon (fingers crossed). 😄
